"""
Shared enumerations and lookup tables for the College Scorecard pipeline.
"""

REGION_MAP = {
    1: "New England",
    2: "Mid East",
    3: "Great Lakes",
    4: "Plains",
    5: "Southeast",
    6: "Southwest",
    7: "Rocky Mountains",
    8: "Far West",
    9: "Outlying Areas",
}

CREDENTIAL_MAP = {
    1: "Undergraduate Certificate",
    2: "Associate's Degree",
    3: "Bachelor's Degree",
    4: "Post-baccalaureate Certificate",
    5: "Master's Degree",
    6: "Doctoral Degree",
    7: "First Professional Degree",
}

STATE_REGION_MAP = {
    "AL": 5,
    "AK": 8,
    "AZ": 6,
    "AR": 5,
    "CA": 8,
    "CO": 7,
    "CT": 1,
    "DE": 2,
    "FL": 5,
    "GA": 5,
    "HI": 8,
    "ID": 7,
    "IL": 3,
    "IN": 3,
    "IA": 4,
    "KS": 4,
    "KY": 5,
    "LA": 5,
    "ME": 1,
    "MD": 2,
    "MA": 1,
    "MI": 3,
    "MN": 4,
    "MS": 5,
    "MO": 4,
    "MT": 7,
    "NE": 4,
    "NV": 8,
    "NH": 1,
    "NJ": 2,
    "NM": 6,
    "NY": 2,
    "NC": 5,
    "ND": 4,
    "OH": 3,
    "OK": 6,
    "OR": 8,
    "PA": 2,
    "RI": 1,
    "SC": 5,
    "SD": 4,
    "TN": 5,
    "TX": 6,
    "UT": 7,
    "VT": 1,
    "VA": 5,
    "WA": 8,
    "WI": 3,
    "WV": 5,
    "WY": 7,
    # Federal district & territories
    "DC": 2,
    "AS": 9,
    "FM": 9,
    "GU": 9,
    "MH": 9,
    "MP": 9,
    "PR": 9,
    "PW": 9,
    "VI": 9,
}


